Fix test in test_traffic_statistics.py
The unittest test_make_url_latest()  was failing with:

ERROR: test _make_latest_url().
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/travis/build/Commonists/wm_metrics/tests/test_traffic_statistics.py",
line 24, in test_make_latest_url
result = traffic._make_latest_url(90)
AttributeError: Traffic instance has no attribute '_make_latest_url'

This was because the method is named _make_url_latest, not _make_latest_url.

Change method call with the correct name.